name: lingo
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.14.0
  equatable: ^2.0.7
  connectivity_plus: ^6.1.4
  internet_connection_checker: ^1.0.0+1
  url_launcher: ^6.3.1
  go_router: ^14.3.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  dartz: ^0.10.1
  http: ^1.2.0
  get_it: ^8.0.1
  google_nav_bar: ^5.0.7
  table_calendar: ^3.2.0
  font_awesome_flutter: ^10.8.0
  cloud_firestore: ^5.6.9
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1
  path_provider: ^2.1.5
  intl: ^0.20.2
  firebase_database: ^11.3.7
  web_socket_channel: ^3.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/logo_foreground.png"

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
